version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Dupa123!
      POSTGRES_USER: postgres@postgres-spring
      POSTGRES_DB: spring
    ports:
      - 5432:5432